name: used-cars-log-trans
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
